# Generated by Django 3.1.2 on 2020-11-11 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Шахто-управление')),
            ],
            options={
                'verbose_name': 'Шахто-управление',
                'verbose_name_plural': 'Шахто-управления',
            },
        ),
        migrations.CreateModel(
            name='Pp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Дроизводственое подраздиление')),
                ('shu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekzamenator.shu', verbose_name='Шахто-управление')),
            ],
            options={
                'verbose_name': 'Дроизводственое подраздиление',
                'verbose_name_plural': 'Дроизводственое подраздиления',
            },
        ),
    ]
