# Generated by Django 3.1.2 on 2020-11-11 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekzamenator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Участок')),
                ('shu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekzamenator.shu', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участоки',
            },
        ),
    ]
