# Generated by Django 3.1.2 on 2020-11-12 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekzamenator', '0003_auto_20201111_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Праффесия')),
            ],
            options={
                'verbose_name': 'Праффесия',
                'verbose_name_plural': 'Праффесии',
            },
        ),
        migrations.AlterModelOptions(
            name='pp',
            options={'ordering': ('name', 'shu'), 'verbose_name': 'Дроизводственое подраздиление', 'verbose_name_plural': 'Дроизводственое подраздиления'},
        ),
        migrations.AlterModelOptions(
            name='uch',
            options={'ordering': ('name', 'shu', 'pp'), 'verbose_name': 'Участок', 'verbose_name_plural': 'Участки'},
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Фамилия И.О.')),
                ('nomer', models.PositiveIntegerField(verbose_name='Номер')),
                ('pp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekzamenator.pp', verbose_name='Дроизводственое подраздилени')),
                ('prof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekzamenator.prof', verbose_name='Проффесия')),
                ('shu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekzamenator.shu', verbose_name='Шахто-управление')),
                ('uch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekzamenator.uch', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
                'ordering': ('name', 'shu', 'pp'),
            },
        ),
    ]
